//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexComm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EB 90 EB 90 32 50 38 30 45 34 54 43 36 31 32 31 30 32 33 30 5B 5B D8 04 81 90 85 " +
            "98 94 85 83 88 50 41 58 45 2D 04 08 02 0E 11 37 1E 2D 04 06 03 12 0F 0A 1E 32 4E" +
            " 30 53 2D 38 38 34 43 35 45 2D 00 54 00 00 00 00 00 00 32 50 38 30 45 34 54 43 3" +
            "6 31 32 31 30 32 33 30 00 00 00 00 02 00 02 00 0A 00 00 8C 07 00 00 08 05 00 00 " +
            "46 03 00 00 84 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00" +
            " 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 0" +
            "0 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 " +
            "25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00 80 25 00 00" +
            " 80 25 00 00 80 25 00 00 80 25 07 07 05 06 08 08 08 08 08 08 08 08 08 08 08 08 0" +
            "8 08 08 08 08 08 08 08 08 08 08 08 08 08 08 08 01 00 03 02 00 00 00 00 00 00 00 " +
            "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0A 00 02 00" +
            " 00 00 02 00 01 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 0" +
            "2 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 00 02 " +
            "00 02 00 02 00 02 00 02 00 00 00 00 00 02 02 02 02 02 02 02 02 02 02 02 02 02 02" +
            " 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 00 00 00 00 00 00 00 00 0" +
            "0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 " +
            "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" +
            " 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0" +
            "0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 " +
            "00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF 0A 00 0A 00 0A 00 0A 00 0A 00" +
            " 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0" +
            "A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A " +
            "00 FF FF FF FF FF FF FF FF A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0" +
            " 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A" +
            "8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C " +
            "00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0" +
            " 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A8 C0 0C 00 A" +
            "8 C0 0C 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D " +
            "00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0" +
            " 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A" +
            "8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D " +
            "00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 A8 C0 0D 00 ED 13" +
            " ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 E" +
            "D 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED " +
            "13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13" +
            " ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 E" +
            "D 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 ED 13 00 00 00 00 00 00 00 " +
            "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" +
            " 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0" +
            "0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 " +
            "00 00 00 00 00 00 00 00 00 00 00 00 00 A8 C0 02 00 A8 C0 03 00 FF FF 00 FF FF FF" +
            " 00 FF A8 C0 01 00 A8 C0 01 00 ED 13 ED 13 00 00 00 00 C0 00 A8 C0 02 00 C0 00 A" +
            "8 C0 03 00 FF FF 00 00 01 00 00 00 FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 " +
            "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" +
            " 00 00 00 00 00 00 AC 26 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0" +
            "0 00 00 00 00 00 00 00 73 55 72 65 31 31 31 31 00 00 00 00 00 00 00 00 00 00 00 " +
            "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 32 31 34 33 36 35" +
            " 38 37 50 41 58 45 00 00 79 FB 8C 4F 03 00")]
        public string HEX {
            get {
                return ((string)(this["HEX"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string PWD {
            get {
                return ((string)(this["PWD"]));
            }
            set {
                this["PWD"] = value;
            }
        }
    }
}
